---
title: "Practice Problems -- Polisci 209"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Practice Problems


#### Chapter 2
1. Exercise Set A, Question 5

2. Exercise Set A, Question 7

2. Exercise Set A, Question 8

3. Exercise Set B, Question 4

3. Exercise Set B, Question 12

#### Chapter 3

1. Exercise Set A, Question 1

1. Exercise Set A, Question 4

1. Exercise Set A, Question 5

1. Exercise Set C, Question 1

1. Exercise Set C, Question 1


#### Chapter 4

1. Exercise Set A, Question 3

1. Exercise Set B, Question 1

1. Exercise Set D, Question 6

1. Exercise Set E, Question 5

1. Exercise Set E, Question 7

#### Chapter 5


1. Exercise Set A, Question 2

1. Exercise Set B, Question 5

1. Exercise Set C, Question 1

1. Exercise Set D, Question 1

1. Exercise Set D, Question 2


#### Chapter 7

1. Exercise Set A, Question 2

1. Exercise Set B, Question 3

1. Exercise Set E, Question 1

1. Exercise Set E, Question 4

#### Chapter 8

1. Exercise Set A, Question 6

1. Exercise Set B, Question 2

1. Exercise Set B, Question 7

1. Exercise Set D, Question 1


#### Chapter 9

1. Exercise Set A, Question 2

1. Exercise Set A, Question 3

1. Exercise Set A, Question 6

1. Exercise Set E, Question 3


#### Chapter 10

1. Exercise Set A, Question 1

1. Exercise Set A, Question 2

1. Exercise Set C, Question 1

1. Exercise Set E, Question 2

1. Exercise Set E, Question 3

#### Chapter 11

1. Exercise Set A, Question 3

1. Exercise Set A, Question 5

1. Exercise Set A, Question 7

1. Exercise Set B, Question 1

1. Exercise Set D, Question 2

1. Exercise Set D, Question 3

1. Exercise Set E, Question 3

#### Chapter 12

1. Exercise Set A, Question 1

1. Exercise Set A, Question 3

1. Exercise Set B, Question 3

#### Chapter 13

1. Exercise Set B, Question 3

1. Exercise Set B, Question 4

1. Exercise Set C, Question 3

1. Exercise Set C, Question 7

1. Exercise Set D, Question 4

1. Exercise Set D, Question 7

#### Chapter 14

1. Exercise Set A, Question 2

1. Exercise Set B, Question 1

1. Exercise Set B, Question 3

1. Exercise Set C, Question 2

1. Exercise Set C, Question 4

1. Exercise Set D, Question 3

1. Exercise Set D, Question 4

#### Chapter 16

1. Exercise Set A, Question 3

1. Exercise Set A, Question 6

1. Exercise Set B, Question 3

1. Exercise Set B, Question 5

1. Exercise Set C, Question 2

#### Chapter 17

1. Exercise Set A, Question 1

1. Exercise Set B, Question 1

1. Exercise Set B, Question 4

1. Exercise Set C, Question 1

1. Exercise Set C, Question 6

1. Exercise Set D, Question 4

1. Exercise Set E, Question 1

1. Exercise Set E, Question 3

1. Exercise Set C, Question 9

#### Chapter 18

1. Exercise Set A, Question 1

1. Exercise Set A, Question 5

1. Exercise Set B, Question 4

1. Exercise Set B, Question 5

1. Exercise Set C, Question 6

#### Chapter 19

1. Exercise Set A, Question 2

1. Exercise Set A, Question 6

1. Exercise Set A, Question 12



#### Chapter 20

1. Exercise Set A, Question 1

1. Exercise Set A, Question 3

1. Exercise Set A, Question 5

1. Exercise Set B, Question 2

1. Exercise Set B, Question 5

1. Exercise Set C, Question 1

1. Exercise Set C, Question 4

#### Chapter 21

1. Exercise Set A, Question 1

1. Exercise Set A, Question 4

1. Exercise Set A, Question 8

1. Exercise Set B, Question 1

1. Exercise Set B, Question 3

1. Exercise Set C, Question 1

1. Exercise Set C, Question 2

1. Exercise Set C, Question 5

1. Exercise Set C, Question 6

1. Exercise Set C, Question 7

#### Chapter 23

1. Exercise Set A, Question 3

1. Exercise Set A, Question 4

1. Exercise Set A, Question 9

1. Exercise Set B, Question 1

1. Exercise Set B, Question 4

1. Exercise Set B, Question 6

1. Exercise Set C, Question 1

#### Chapter 24

1. Exercise Set A, Question 4

1. Exercise Set A, Question 5

1. Exercise Set B, Question 1

1. Exercise Set B, Question 2

1. Exercise Set B, Question 5

1. Exercise Set C, Question 2

1. Exercise Set C, Question 4

1. Exercise Set D, Question 3

1. Exercise Set E, Question 7

1. Exercise Set E, Question 9

1. Exercise Set F, Question 3

#### Chapter 25

1. Exercise Set A, Question 4

1. Exercise Set A, Question 6

1. Exercise Set B, Question 2

1. Exercise Set B, Question 4

1. Exercise Set C, Question 2

1. Exercise Set C, Question 3

1. Exercise Set D, Question 2

1. Exercise Set D, Question 4

1. Exercise Set D, Question 7





























































































