---
title: "Writing Assignment 3 -- Polisci 209"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Writing Assignment 3
#### First Draft due on November 20th, Final Paper due on December 4th

For this assignment you need to download the "guns.csv" data file from the course website. Here is a link to the data: [https://fhollenbach.github.io/polisci209_fall2017/img/images/data/guns.csv](https://fhollenbach.github.io/polisci209_fall2017/img/images/data/guns.csv). Read the data into _RStudio_ and play around for a bit. There are a lot of different variables in this dataset. The variables included are the following:

- __state__: the full name of the state.
- __state_abbr__: the state’s two-letter abbreviation.
- __firearm_death_rate__: the (age-adjusted) death rate due to firearms per 100,000 in 2014. Suicides,
accidental deaths, and homicides are included in this category, if the death was causes by a gun.
- __homicide_death_rate__: the (age-adjusted) death rate due to homicide per 100,000 in 2014. These
homicides do not necessarily involve firearms.
- 134 other variables that may be of interest and are laws potentially related to gun deaths. These data come from the statefirearmlaws database, which you can find here: [https://www.statefirearmlaws.org](https://www.statefirearmlaws.org/). The first thing you should do is find definitions of all the different variables in the code book. The last variable "lawtotal" is a summary of all the different laws, i.e. a total score of how many (restricting/controlling) laws are in place in a given state. The code book is located here: [https://fhollenbach.github.io/polisci209_fall2017/img/images/data/codebook_guns.xls](https://fhollenbach.github.io/polisci209_fall2017/img/images/data/codebook_guns.xls)


Your task is to use the guns.csv dataset and write a report about two variables chosen from the set of independent variables above and their relationship to the __firearm_death_rate__ or the __homicide_death_rate__. __What, if any, are the policy implications of two variables you analysed on the outcomes of firearm-related deaths or homicide deaths?__

## Framing Your Analysis
 You can choose to frame your analysis in a number of ways, provided it incorporates the above elements. You should make an argument for why you do so. Here are some questions you might consider: 
 
- Which outcome variable (firearm related deaths or homicide deaths) is the more policy-relevant, and why?
- What causal models related to the policies and outcomes are plausible? What model do you think is the most (or least) compelling? 
- How should policy change if the causal claim you analyze is true, if at all?  What if it is false?
- __Write this paper as if you do not have a political opinion on the matter. The result should be an objective report of the relationship between two explanatory variables (your choice) and one of the two outcome measures.__ 

\pagebreak

## Structuring Your Paper:
Your essay should contain the following three (3) sections: 
 
###Introduction:  

Give an overview of your paper and explain why others should care about the topic. Why is it important? 

###Framing and Description:  

  - Identify one outcome and two explanatory variables of interest. Explain why you think these are the most policy-relevant. (Justify why firearm-related deaths or homicide deaths matters more. Justify why your chosen independent variables are the relevant explanatory variables.)
  - Describe the averages and standard deviations of __all__ chosen variables.
  - Create a scatterplot of and calculate the correlation between your variables of interest and the  outcome of choice (i.e. this means a total of two scatterplots, one for each explanatory variable). Rather than use geom_point(), use geom_text() and include the __label = state_abbr__ as an aesthetic.
  - Briefly interpret the correlations and scatterplots. You may also want to check what the correlation between your two explanatory variables is.

### Regression Analysis

In this section, you will use regression to evaluate the evidence for the relatioships. You need to do the following:  
  
  - Run a regression for each of the two independent variables with your outcome variables. This means  creating two separate regression tables.
  - Interpret the coefficients. (For instance: a 1-point increase in lawtotal predicts a decrease in the firearm_death_rate by 0.12).
  - What evidence, if any, does the regression provide for the effectiveness of the policy?
  - Discuss the policy implications.
  - Lastly, create a regression that has your outcome variable as the dependent variable (y) and includes both explanatory variables as independent variables. Code example: 
  `# fit linear model with multiple independent variables
fit <- lm(firearm_death_rate ~ immunity + gunshow, data = guns)`
  - Does this change the conclusion? If so, how?
  
### Conclusion

Give your readers an overview of the paper and leave them with a takeaway—your key point. Leave the readers with a stark conclusion about how the data and your analysis should inform policymakers and the public about gun policy in the U.S. Again, __try to leave the paper free of your personal opinion. Any statements should be the result of your data analysis.__

## Notes:
- You must upload the initial submission of your first draft (still a polished draft, not a rough draft) through eCampus by 6pm on Monday, November 20. The final paper will be due via eCampus at noon on December 4th. 
- __I do not tolerate plagiarism__. You can find the Honor System Rules here: [http://student-rules.tamu.edu/aggiecode](http://student-rules.tamu.edu/aggiecode). __You should note that even seemingly minor violations can become a permanent addition to your transcript.__ 
- This is a short research paper in political science, thus it necessarily is about politics. Yet, you __should leave you personal political opinions out of this paper__. You are not writing a paper to reflect your normative opinions about guns, but rather a research paper that objectively looks at some data.
- The paper must contain at least 500 words. I welcome additional effort, but I encourage you to focus on fitting more content into fewer words rather than submitting a long paper. 
- You should make the paper look and sound professional, but I encourage you to be creative and playful with your prose. Remember, others will read your writing. Make it enjoyable. 
- You should write the paper so that someone who has not had this class could read it. Perhaps imagine writing to your parents. Suppose this person is interested in politics—they’ll be excited to read your ideas—but not knowledgeable about statistics (e.g., they don’t know what a standard deviation is).


##Formatting 
- 12 point, Times New Roman Font, for the main body text.
- Double-space the main body of the text.
- Use section and subsection headings, with larger or different font as you see fit. 
- 1 inch margins.
- Include your name, the title of your paper, and the word count on the first page of your paper. (Note, the minimum is 500 words).
- Make sure all graphs and plots are clearly labeled and identified in the text.
- Include page numbers on the top right-hand corner of the page.
- Beyond the points above, I simply want your paper to look professional and give you room to match the format to your aesthetic preferences. 

## References 
- Make sure to properly cite any sources you incorporate, and include a reference list.  


\pagebreak